name: 'POEditor Export'
description: 'Exports translation file'
author: 'Stanislav Cherenkov'

inputs:
  api_token:
    description: 'POEditor API token, read-only is enough'
    required: true
  project_id:
    description: 'The exported project ID'
    required: true
  language:
    description: 'The exported language code'
    required: true
    default: en
  output_type:
    description: 'The file format, see https://poeditor.com/docs/api#projects_export'
    required: true

outputs:
  file_path:
    description: 'Exported translation file path'

runs:
  using: node20
  main: dist/index.js
